package org.dfnd.pricks.constants;

public enum StatTypes
{
	POWER, TOUGHNESS, VITALITY, HEALING_POWER, PRECISION, CONDITION_DAMAGE, CONDITION_DURATION, CRITICAL_DAMAGE, BOON_DURATION, ARMOR, ATTACK, CRITICAL_CHANCE, HEALTH, AGONY_RESISTANCE
}
